version: '3'


services:
  postgres:
    image: 'postgres:16.0'
    container_name: java-postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=myCryptoDb'
    ports:
      - "5432:5432"

  app:
    build: ./
    container_name: java-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java-postgres:5432/myCryptoDb?currentSchema=public
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres